# Generated by Django 4.0.2 on 2022-09-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_direccion_p_moral_p_fisica_inmuebles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmuebles',
            name='op_compra',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
