# Generated by Django 4.0.2 on 2022-09-07 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_alter_form_test_user_alter_form_test_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmuebles',
            old_name='alies_inmueble',
            new_name='alias_inmueble',
        ),
        migrations.RenameField(
            model_name='inmuebles',
            old_name='estacionamiento',
            new_name='estatus_gravamem',
        ),
        migrations.RenameField(
            model_name='inmuebles',
            old_name='estatus',
            new_name='estatus_inmueble',
        ),
        migrations.RenameField(
            model_name='inmuebles',
            old_name='uso_inmubele',
            new_name='n_medios_baños',
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='alberca',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='amueblado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='area_comun',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='bar',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='busniess_center',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='cocina',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='cuarto_lavado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='cuota_mantenimiento',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='espacio_deportivo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='estacionamiento_cajones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='gym',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='roof_garden',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='sala_cine',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='sala_juegos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='salon_estudio',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='salon_eventos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='seguridad',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='terraza',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='uso_inmueble',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='venta',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='p_fisica',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='garaje',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='renta',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='valor_inmueble',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
