# Generated by Django 4.0.2 on 2022-09-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_p_moral_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmuebles',
            old_name='aguaPotable',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='inmuebles',
            old_name='caracteristicasExtra',
            new_name='n_pisos',
        ),
        migrations.RenameField(
            model_name='inmuebles',
            old_name='jardin',
            new_name='referencias',
        ),
        migrations.RemoveField(
            model_name='inmuebles',
            name='serviciosExtra',
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='agua_potable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='area_juegos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='año_contruccion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='op_compra',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='otroA',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='restaurante_bar',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='terminos_condiciones',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='camarasSeguridad',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='drenaje',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='electricidad',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='gas',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='internet',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='lineaTelefonica',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='televisionCable',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
