# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from calendar import c
from pyexpat import model
from tabnanny import verbose
from tkinter.tix import Tree
from unittest.util import _MAX_LENGTH
from django.db import models
from django.contrib.auth.models import User


class Rol(models.Model):
      id = models.AutoField(primary_key=True)
      Name=models.CharField(max_length=20)
      created=models.DateTimeField(auto_now_add=True)
      updated=models.DateTimeField(auto_now_add=True)
      class Meta:
            verbose_name="Rol"
            verbose_name_plural="Roles"
      def __str__(self):
            return self.Name

class Profile(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    roles =models.ManyToManyField(Rol)
    direccion=models.CharField(max_length=10,null=True)

class p_moral(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    nombre=models.CharField(max_length=30, blank=True)
    nombre1=models.CharField(max_length=30,null=True, blank=True)
    apellido= models.CharField(max_length=30, null=True, blank=True)
    apellido1=models.CharField(max_length=30, null=True, blank=True)
    n_conyuge=models.CharField(max_length=30, null=True, blank=True)
    n_conyuge1=models.CharField(max_length=30, null=True, blank=True)
    a_conyuge=models.CharField(max_length=30, null=True, blank=True)
    a1_conyuge=models.CharField(max_length=30, null=True, blank=True)    
    numeroTel=models.PositiveIntegerField(null=True, blank=True) 
    numeroTel1=models.PositiveIntegerField(null=True, blank=True) 
    email=models.EmailField(blank=True)
    estado_civil=models.CharField(max_length=30,null=True, blank=True)
    calle=models.CharField(max_length=30, null=True, blank=True)
    municipio_alcaldia=models.CharField(max_length=30, null=True, blank=True)
    colonia=models.CharField(max_length=30, null=True, blank=True)
    estado=models.CharField(max_length=30, null=True, blank=True)
    num_ext=models.PositiveIntegerField(null=True, blank=True)
    num_int=models.PositiveIntegerField(null=True, blank=True)
    codigopostal=models.PositiveIntegerField(null=True, blank=True)
    referencias=models.CharField(max_length=30, null=True, blank=True)
    razon_social=models.CharField(max_length=30, null=True, blank=True)
    rfc=models.CharField(max_length=13, null=True, blank=True)
    numeroTel_empresa=models.PositiveIntegerField(null=True, blank=True)
    email_empresa=models.EmailField(null=True, blank=True)
    nombre_representante=models.CharField(max_length=30, null=True, blank=True)
    nombre1_representante=models.CharField(max_length=30, null=True, blank=True)
    apellido_representante=models.CharField(max_length=30,null=True, blank=True)
    apellido1_representante=models.CharField(max_length=30, null=True, blank=True)
    rfc_representante=models.CharField(max_length=13, null=True, blank=True)
    rfc_empresa=models.CharField(max_length=13, null=True, blank=True)
    numeroTel_representante=models.PositiveIntegerField(null=True, blank=True)
    codigopostalF=models.PositiveIntegerField(null=True, blank=True)
    municipio_alcaldiaF=models.CharField(max_length=30, null=True, blank=True)
    coloniaF=models.CharField(max_length=30,null=True, blank=True)
    estadoF=models.CharField(max_length=30, null=True, blank=True)
    num_extF=models.PositiveIntegerField(null=True, blank=True)
    num_intF=models.PositiveIntegerField(null=True, blank=True)
    calleF=models.CharField(max_length=30, null=True, blank=True)
    referenciasF=models.CharField(max_length=30, null=True, blank=True)
    n_ref1=models.CharField(max_length=30, null=True, blank=True)
    p_ref1=models.CharField(max_length=30, null=True, blank=True)
    tel_ref1=models.PositiveIntegerField(null=True, blank=True)
    n_ref2=models.CharField(max_length=30, null=True, blank=True)
    p_ref2=models.CharField(max_length=30, null=True, blank=True)
    tel_ref2=models.PositiveIntegerField(null=True, blank=True)
    n_ref3=models.CharField(max_length=30, null=True, blank=True)
    p_ref3=models.CharField(max_length=30, null=True, blank=True)
    tel_ref3=models.PositiveIntegerField(null=True, blank=True)
    n_ocupara_inmueble1=models.CharField(max_length=30, null=True, blank=True)
    p_ocupara_inmueble1=models.CharField(max_length=30, null=True, blank=True)
    n_ocupara_inmueble2=models.CharField(max_length=30, null=True, blank=True)
    p_ocupara_inmueble2=models.CharField(max_length=30, null=True, blank=True)
    url_domicilio=models.CharField(max_length=255, null=True, blank=True)
    url_ine=models.CharField(max_length=255, null=True, blank=True)
    url_situacion_fiscal=models.CharField(max_length=255, null=True, blank=True)
    n_fiador=models.CharField(max_length=30, null=True, blank=True)
    n2_fiador=models.CharField(max_length=30, null=True, blank=True)
    a_fiador=models.CharField(max_length=30, null=True, blank=True)
    a2_fiador=models.CharField(max_length=30, null=True, blank=True)
    p_fiador=models.CharField(max_length=30, null=True, blank=True)
    tel_fiador=models.PositiveIntegerField(null=True, blank=True)
    tel2_fiador=models.PositiveIntegerField(null=True, blank=True)
    email_fiador=models.CharField(max_length=30,null=True, blank=True)
    estado_civil_fiador=models.CharField(max_length=30, null=True, blank=True)
    calle_fiador=models.CharField(max_length=30, null=True, blank=True)
    municipio_fiador=models.CharField(max_length=30, null=True, blank=True)
    colonia_fiador=models.CharField(max_length=30,null=True, blank=True)
    estado_fiador=models.CharField(max_length=30, null=True, blank=True)
    n_ext_fiador=models.PositiveIntegerField(null=True, blank=True)
    n_int_fiador=models.PositiveIntegerField(null=True, blank=True)
    cp_fiador=models.PositiveIntegerField(null=True, blank=True)
    referencias_fiador=models.CharField(max_length=30, null=True, blank=True)
    empleador_empresa_fiador=models.CharField(max_length=30, null=True, blank=True)
    empleador_profesion_fiador=models.CharField(max_length=30, null=True, blank=True)
    empleador_tel_fiador=models.PositiveIntegerField(null=True, blank=True)
    empleador_ingreso_fiador=models.PositiveIntegerField(null=True, blank=True)
    recibos=models.CharField(max_length=18, null=True, blank=True)
    created=models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated=models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        db_table = 'PersonaMoral'

class p_fisica(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    nombre=models.CharField(max_length=30, blank=True)
    nombre1=models.CharField(max_length=30,null=True, blank=True)
    apellido= models.CharField(max_length=30, null=True, blank=True)
    apellido1=models.CharField(max_length=30, null=True, blank=True)
    n_conyuge=models.CharField(max_length=30, null=True, blank=True)
    n_conyuge1=models.CharField(max_length=30, null=True, blank=True)
    a_conyuge=models.CharField(max_length=30, null=True, blank=True)
    a1_conyuge=models.CharField(max_length=30, null=True, blank=True)    
    numeroTel=models.PositiveIntegerField(null=True, blank=True) 
    numeroTel1=models.PositiveIntegerField(null=True, blank=True) 
    email=models.EmailField(blank=True)
    estado_civil=models.CharField(max_length=30,null=True, blank=True)
    calle=models.CharField(max_length=30, null=True, blank=True)
    municipio_alcaldia=models.CharField(max_length=30, null=True, blank=True)
    colonia=models.CharField(max_length=30, null=True, blank=True)
    estado=models.CharField(max_length=30, null=True, blank=True)
    num_ext=models.PositiveIntegerField(null=True, blank=True)
    num_int=models.PositiveIntegerField(null=True, blank=True)
    codigopostal=models.PositiveIntegerField(null=True, blank=True)
    referencias=models.CharField(max_length=30, null=True, blank=True)
    razon_social=models.CharField(max_length=30, null=True, blank=True)
    rfc=models.CharField(max_length=13, null=True, blank=True)
    numeroTel_empresa=models.PositiveIntegerField(null=True, blank=True)
    email_empresa=models.EmailField(null=True, blank=True)
    nombre_representante=models.CharField(max_length=30, null=True, blank=True)
    nombre1_representante=models.CharField(max_length=30, null=True, blank=True)
    apellido_representante=models.CharField(max_length=30,null=True, blank=True)
    apellido1_representante=models.CharField(max_length=30, null=True, blank=True)
    rfc_representante=models.CharField(max_length=13, null=True, blank=True)
    rfc_empresa=models.CharField(max_length=13, null=True, blank=True)
    numeroTel_representante=models.PositiveIntegerField(null=True, blank=True)
    codigopostalF=models.PositiveIntegerField(null=True, blank=True)
    municipio_alcaldiaF=models.CharField(max_length=30, null=True, blank=True)
    coloniaF=models.CharField(max_length=30,null=True, blank=True)
    estadoF=models.CharField(max_length=30, null=True, blank=True)
    num_extF=models.PositiveIntegerField(null=True, blank=True)
    num_intF=models.PositiveIntegerField(null=True, blank=True)
    calleF=models.CharField(max_length=30, null=True, blank=True)
    referenciasF=models.CharField(max_length=30, null=True, blank=True)
    n_ref1=models.CharField(max_length=30, null=True, blank=True)
    p_ref1=models.CharField(max_length=30, null=True, blank=True)
    tel_ref1=models.PositiveIntegerField(null=True, blank=True)
    n_ref2=models.CharField(max_length=30, null=True, blank=True)
    p_ref2=models.CharField(max_length=30, null=True, blank=True)
    tel_ref2=models.PositiveIntegerField(null=True, blank=True)
    n_ref3=models.CharField(max_length=30, null=True, blank=True)
    p_ref3=models.CharField(max_length=30, null=True, blank=True)
    tel_ref3=models.PositiveIntegerField(null=True, blank=True)
    n_ocupara_inmueble1=models.CharField(max_length=30, null=True, blank=True)
    p_ocupara_inmueble1=models.CharField(max_length=30, null=True, blank=True)
    n_ocupara_inmueble2=models.CharField(max_length=30, null=True, blank=True)
    p_ocupara_inmueble2=models.CharField(max_length=30, null=True, blank=True)
    url_domicilio=models.CharField(max_length=255, null=True, blank=True)
    url_ine=models.CharField(max_length=255, null=True, blank=True)
    url_situacion_fiscal=models.CharField(max_length=255, null=True, blank=True)
    n_fiador=models.CharField(max_length=30, null=True, blank=True)
    n2_fiador=models.CharField(max_length=30, null=True, blank=True)
    a_fiador=models.CharField(max_length=30, null=True, blank=True)
    a2_fiador=models.CharField(max_length=30, null=True, blank=True)
    p_fiador=models.CharField(max_length=30, null=True, blank=True)
    tel_fiador=models.PositiveIntegerField(null=True, blank=True)
    tel2_fiador=models.PositiveIntegerField(null=True, blank=True)
    email_fiador=models.CharField(max_length=30,null=True, blank=True)
    estado_civil_fiador=models.CharField(max_length=30, null=True, blank=True)
    calle_fiador=models.CharField(max_length=30, null=True, blank=True)
    municipio_fiador=models.CharField(max_length=30, null=True, blank=True)
    colonia_fiador=models.CharField(max_length=30,null=True, blank=True)
    estado_fiador=models.CharField(max_length=30, null=True, blank=True)
    n_ext_fiador=models.PositiveIntegerField(null=True, blank=True)
    n_int_fiador=models.PositiveIntegerField(null=True, blank=True)
    cp_fiador=models.PositiveIntegerField(null=True, blank=True)
    referencias_fiador=models.CharField(max_length=30, null=True, blank=True)
    empleador_empresa_fiador=models.CharField(max_length=30, null=True, blank=True)
    empleador_profesion_fiador=models.CharField(max_length=30, null=True, blank=True)
    empleador_tel_fiador=models.PositiveIntegerField(null=True, blank=True)
    empleador_ingreso_fiador=models.PositiveIntegerField(null=True, blank=True)
    recibos=models.CharField(max_length=18, null=True, blank=True)
    created=models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated=models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        db_table = 'PersonaFisica'

class form_test(models.Model):
    id = models.AutoField(primary_key=True)
    user=models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    nombre=models.CharField(max_length=30)
    nombre1=models.CharField(max_length=30)

    class Meta:
        db_table = 'PRUEBAS'

class inmuebles(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    alias_inmueble = models.CharField(max_length=30, null=True, blank=True)
    estatus_inmueble = models.CharField(max_length=30, null=True, blank=True)
    renta = models.PositiveIntegerField(null=True, blank=True)
    venta = models.PositiveIntegerField(null=True, blank=True)
    clave_catastral = models.CharField(max_length=30, null=True, blank=True)
    estatus_gravamem = models.CharField(max_length=30, null=True, blank=True)
    valor_inmueble = models.PositiveIntegerField(null=True, blank=True)
    cuota_mantenimiento= models.PositiveIntegerField(null=True, blank=True)
    tipo_inmueble = models.CharField(max_length=30, null=True, blank=True)
    uso_inmueble= models.CharField(max_length=30, null=True, blank=True)
    op_compra = models.CharField(max_length=30, null=True, blank=True)
    municipio_alcaldia = models.CharField(max_length=30, null=True, blank=True)
    colonia = models.CharField(max_length=30, null=True, blank=True)
    postal_code = models.CharField(max_length=30, null=True, blank=True)
    estado  = models.CharField(max_length=30, null=True, blank=True)
    calle = models.CharField(max_length=30, null=True, blank=True)
    numeroExterior = models.CharField(max_length=30, null=True, blank=True)
    numeroInterior = models.CharField(max_length=30, null=True, blank=True)
    calle1 = models.CharField(max_length=30, null=True, blank=True)
    calle2 = models.CharField(max_length=30, null=True, blank=True)
    referencias = models.CharField(max_length=30, null=True, blank=True)
    n_baños = models.PositiveIntegerField(null=True, blank=True)
    n_medios_baños = models.PositiveIntegerField(null=True, blank=True)
    n_recamaras = models.PositiveIntegerField(null=True, blank=True)
    n_pisos = models.PositiveIntegerField(null=True, blank=True)
    estacionamiento_cajones = models.PositiveIntegerField(null=True, blank=True)
    terrenoContruido  = models.PositiveIntegerField(null=True, blank=True)
    terrenoTotal = models.PositiveIntegerField(null=True, blank=True)    
    año_contruccion = models.PositiveIntegerField(null=True, blank=True)
    garaje = models.CharField(max_length=30, null=True, blank=True)
    terraza =  models.CharField(max_length=30, null=True, blank=True)
    alberca =  models.CharField(max_length=30, null=True, blank=True)
    cocina =  models.CharField(max_length=30, null=True, blank=True)
    amueblado = models.CharField(max_length=30, null=True, blank=True)
    cuarto_lavado =models.CharField(max_length=30, null=True, blank=True)
    mascotas  = models.CharField(max_length=30, null=True, blank=True)
    gym = models.CharField(max_length=30, null=True, blank=True)
    bar = models.CharField(max_length=30, null=True, blank=True)
    restaurante_bar=models.CharField(max_length=30, null=True, blank=True)
    sala_cine = models.CharField(max_length=30, null=True, blank=True)
    salon_estudio = models.CharField(max_length=30, null=True, blank=True)
    area_comun = models.CharField(max_length=30, null=True, blank=True)
    sala_juegos = models.CharField(max_length=30, null=True, blank=True)
    salon_eventos = models.CharField(max_length=30, null=True, blank=True)
    espacio_deportivo = models.CharField(max_length=30, null=True, blank=True)
    busniess_center = models.CharField(max_length=30, null=True, blank=True)
    roof_garden = models.CharField(max_length=30, null=True, blank=True)
    otroA = models.CharField(max_length=30, null=True, blank=True)
    internet  = models.CharField(max_length=30, null=True, blank=True)
    electricidad  = models.CharField(max_length=30, null=True, blank=True)    
    agua_potable = models.CharField(max_length=30, null=True, blank=True)
    televisionCable = models.CharField(max_length=30, null=True, blank=True)
    gas = models.CharField(max_length=30, null=True, blank=True)
    lineaTelefonica = models.CharField(max_length=30, null=True, blank=True)
    drenaje = models.CharField(max_length=30, null=True, blank=True)
    seguridad = models.CharField(max_length=30, null=True, blank=True)
    camarasSeguridad  = models.CharField(max_length=30, null=True, blank=True)
    area_juegos = models.CharField(max_length=30, null=True, blank=True)
    otroS = models.CharField(max_length=30, null=True, blank=True)
    # imagenes=models.ImageField(upload_to='imagenes', upload_to='fotos', blank=True)
    fotosInmueble = models.CharField(max_length=30, null=True, blank=True)
    descripcion= models.CharField(max_length=30, null=True, blank=True)
    terminos_condiciones = models.CharField(max_length=30, null=True, blank=True)

    class Meta:
        db_table = 'Inmuebles'

# class productos(models.Model):
#     id = models.AutoField(primary_key=True)
#     tipo_producto = models.CharField(max_length=30, null=True, blank=True)
#     nombre_producto = models.CharField(max_length=30, null=True, blank=True) 
#     categoria_producto = models.CharField(max_length=50, null=True, blank=True)
#     etiqueta_producto = models.CharField(max_length=50, null=True, blank=True)
#     costo_producto = models.CharField(max_length=50, null=True, blank=True)
#     descripción_producto = models.CharField(max_length=50, null=True, blank=True)

#     class Meta:
#         db_table = 'Productos'

# class paquetes(models.Model):
#     id = models.AutoField(primary_key=True)
#     producto = models.ForeignKey(productos, null = True, blank = True, on_delete=models.CASCADE)
#     tipo_paquete = models.CharField(max_length=30, null=True, blank=True)
#     nombre_paquete = models.CharField(max_length=30, null=True, blank=True) 
#     categoria_paquete = models.CharField(max_length=50, null=True, blank=True)
#     etiqueta_paquete = models.CharField(max_length=50, null=True, blank=True)
#     costo_paquete = models.CharField(max_length=50, null=True, blank=True)
#     descripción_paquete = models.CharField(max_length=50, null=True, blank=True)

#     class Meta:
#         db_table = 'Paquetes'
