# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from pyexpat import model
from tabnanny import verbose
from unittest.util import _MAX_LENGTH
from django.db import models
from django.contrib.auth.models import User


class Rol(models.Model):
      id = models.AutoField(primary_key=True)
      Name=models.CharField(max_length=20)
      created=models.DateTimeField(auto_now_add=True)
      updated=models.DateTimeField(auto_now_add=True)
      class Meta:
            verbose_name="Rol"
            verbose_name_plural="Roles"
      def __str__(self):
            return self.Name

class Profile(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    roles =models.ManyToManyField(Rol)
    direccion=models.CharField(max_length=10,null=True)

class p_moral(models.Model):
    id = models.AutoField(primary_key=True)
    nombre=models.CharField(max_length=30, blank=True)
    nombre1=models.CharField(max_length=30,null=True, blank=True)
    apellido= models.CharField(max_length=30, null=True, blank=True)
    apellido1=models.CharField(max_length=30, null=True, blank=True)
    n_conyuge=models.CharField(max_length=30, null=True, blank=True)
    n_conyuge1=models.CharField(max_length=30, null=True, blank=True)
    a_conyuge=models.CharField(max_length=30, null=True, blank=True)
    a1_conyuge=models.CharField(max_length=30, null=True, blank=True)    
    numeroTel=models.PositiveIntegerField(null=True, blank=True) 
    numeroTel1=models.PositiveIntegerField(null=True, blank=True) 
    email=models.EmailField(blank=True)
    estado_civil=models.CharField(max_length=30,null=True, blank=True)
    calle=models.CharField(max_length=30, null=True, blank=True)
    municipio_alcaldia=models.CharField(max_length=30, null=True, blank=True)
    colonia=models.CharField(max_length=30, null=True, blank=True)
    estado=models.CharField(max_length=30, null=True, blank=True)
    num_ext=models.PositiveIntegerField(null=True, blank=True)
    num_int=models.PositiveIntegerField(null=True, blank=True)
    codigopostal=models.PositiveIntegerField(null=True, blank=True)
    referencias=models.CharField(max_length=30, null=True, blank=True)
    razon_social=models.CharField(max_length=30, null=True, blank=True)
    rfc=models.CharField(max_length=13, null=True, blank=True)
    numeroTel_empresa=models.PositiveIntegerField(null=True, blank=True)
    email_empresa=models.EmailField(null=True, blank=True)
    nombre_representante=models.CharField(max_length=30, null=True, blank=True)
    nombre1_representante=models.CharField(max_length=30, null=True, blank=True)
    apellido_representante=models.CharField(max_length=30,null=True, blank=True)
    apellido1_representante=models.CharField(max_length=30, null=True, blank=True)
    rfc_representante=models.CharField(max_length=13, null=True, blank=True)
    rfc_empresa=models.CharField(max_length=13, null=True, blank=True)
    numeroTel_representante=models.PositiveIntegerField(null=True, blank=True)
    codigopostalF=models.PositiveIntegerField(null=True, blank=True)
    municipio_alcaldiaF=models.CharField(max_length=30, null=True, blank=True)
    coloniaF=models.CharField(max_length=30,null=True, blank=True)
    estadoF=models.CharField(max_length=30, null=True, blank=True)
    num_extF=models.PositiveIntegerField(null=True, blank=True)
    num_intF=models.PositiveIntegerField(null=True, blank=True)
    calleF=models.CharField(max_length=30, null=True, blank=True)
    referenciasF=models.CharField(max_length=30, null=True, blank=True)
    n_ref1=models.CharField(max_length=30, null=True, blank=True)
    p_ref1=models.CharField(max_length=30, null=True, blank=True)
    tel_ref1=models.PositiveIntegerField(null=True, blank=True)
    n_ref2=models.CharField(max_length=30, null=True, blank=True)
    p_ref2=models.CharField(max_length=30, null=True, blank=True)
    tel_ref2=models.PositiveIntegerField(null=True, blank=True)
    n_ref3=models.CharField(max_length=30, null=True, blank=True)
    p_ref3=models.CharField(max_length=30, null=True, blank=True)
    tel_ref3=models.PositiveIntegerField(null=True, blank=True)
    n_ocupara_inmueble1=models.CharField(max_length=30, null=True, blank=True)
    p_ocupara_inmueble1=models.CharField(max_length=30, null=True, blank=True)
    n_ocupara_inmueble2=models.CharField(max_length=30, null=True, blank=True)
    p_ocupara_inmueble2=models.CharField(max_length=30, null=True, blank=True)
    url_domicilio=models.CharField(max_length=255, null=True, blank=True)
    url_ine=models.CharField(max_length=255, null=True, blank=True)
    url_situacion_fiscal=models.CharField(max_length=255, null=True, blank=True)
    n_fiador=models.CharField(max_length=30, null=True, blank=True)
    n2_fiador=models.CharField(max_length=30, null=True, blank=True)
    a_fiador=models.CharField(max_length=30, null=True, blank=True)
    a2_fiador=models.CharField(max_length=30, null=True, blank=True)
    p_fiador=models.CharField(max_length=30, null=True, blank=True)
    tel_fiador=models.PositiveIntegerField(null=True, blank=True)
    tel2_fiador=models.PositiveIntegerField(null=True, blank=True)
    email_fiador=models.CharField(max_length=30,null=True, blank=True)
    estado_civil_fiador=models.CharField(max_length=30, null=True, blank=True)
    calle_fiador=models.CharField(max_length=30, null=True, blank=True)
    municipio_fiador=models.CharField(max_length=30, null=True, blank=True)
    colonia_fiador=models.CharField(max_length=30,null=True, blank=True)
    estado_fiador=models.CharField(max_length=30, null=True, blank=True)
    n_ext_fiador=models.PositiveIntegerField(null=True, blank=True)
    n_int_fiador=models.PositiveIntegerField(null=True, blank=True)
    cp_fiador=models.PositiveIntegerField(null=True, blank=True)
    referencias_fiador=models.CharField(max_length=30, null=True, blank=True)
    empleador_empresa_fiador=models.CharField(max_length=30, null=True, blank=True)
    empleador_profesion_fiador=models.CharField(max_length=30, null=True, blank=True)
    empleador_tel_fiador=models.PositiveIntegerField(null=True, blank=True)
    empleador_ingreso_fiador=models.PositiveIntegerField(null=True, blank=True)
    recibos=models.CharField(max_length=18, null=True, blank=True)
    created=models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated=models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        db_table = 'PersonaMoral'

class p_fisica(models.Model):
    id = models.AutoField(primary_key=True)
    nombre=models.CharField(max_length=30, blank=True)
    nombre1=models.CharField(max_length=30,null=True, blank=True)
    apellido= models.CharField(max_length=30, null=True, blank=True)
    apellido1=models.CharField(max_length=30, null=True, blank=True)
    n_conyuge=models.CharField(max_length=30, null=True, blank=True)
    n_conyuge1=models.CharField(max_length=30, null=True, blank=True)
    a_conyuge=models.CharField(max_length=30, null=True, blank=True)
    a1_conyuge=models.CharField(max_length=30, null=True, blank=True)    
    numeroTel=models.PositiveIntegerField(null=True, blank=True) 
    numeroTel1=models.PositiveIntegerField(null=True, blank=True) 
    email=models.EmailField(blank=True)
    estado_civil=models.CharField(max_length=30,null=True, blank=True)
    calle=models.CharField(max_length=30, null=True, blank=True)
    municipio_alcaldia=models.CharField(max_length=30, null=True, blank=True)
    colonia=models.CharField(max_length=30, null=True, blank=True)
    estado=models.CharField(max_length=30, null=True, blank=True)
    num_ext=models.PositiveIntegerField(null=True, blank=True)
    num_int=models.PositiveIntegerField(null=True, blank=True)
    codigopostal=models.PositiveIntegerField(null=True, blank=True)
    referencias=models.CharField(max_length=30, null=True, blank=True)
    razon_social=models.CharField(max_length=30, null=True, blank=True)
    rfc=models.CharField(max_length=13, null=True, blank=True)
    numeroTel_empresa=models.PositiveIntegerField(null=True, blank=True)
    email_empresa=models.EmailField(null=True, blank=True)
    nombre_representante=models.CharField(max_length=30, null=True, blank=True)
    nombre1_representante=models.CharField(max_length=30, null=True, blank=True)
    apellido_representante=models.CharField(max_length=30,null=True, blank=True)
    apellido1_representante=models.CharField(max_length=30, null=True, blank=True)
    rfc_representante=models.CharField(max_length=13, null=True, blank=True)
    rfc_empresa=models.CharField(max_length=13, null=True, blank=True)
    numeroTel_representante=models.PositiveIntegerField(null=True, blank=True)
    codigopostalF=models.PositiveIntegerField(null=True, blank=True)
    municipio_alcaldiaF=models.CharField(max_length=30, null=True, blank=True)
    coloniaF=models.CharField(max_length=30,null=True, blank=True)
    estadoF=models.CharField(max_length=30, null=True, blank=True)
    num_extF=models.PositiveIntegerField(null=True, blank=True)
    num_intF=models.PositiveIntegerField(null=True, blank=True)
    calleF=models.CharField(max_length=30, null=True, blank=True)
    referenciasF=models.CharField(max_length=30, null=True, blank=True)
    n_ref1=models.CharField(max_length=30, null=True, blank=True)
    p_ref1=models.CharField(max_length=30, null=True, blank=True)
    tel_ref1=models.PositiveIntegerField(null=True, blank=True)
    n_ref2=models.CharField(max_length=30, null=True, blank=True)
    p_ref2=models.CharField(max_length=30, null=True, blank=True)
    tel_ref2=models.PositiveIntegerField(null=True, blank=True)
    n_ref3=models.CharField(max_length=30, null=True, blank=True)
    p_ref3=models.CharField(max_length=30, null=True, blank=True)
    tel_ref3=models.PositiveIntegerField(null=True, blank=True)
    n_ocupara_inmueble1=models.CharField(max_length=30, null=True, blank=True)
    p_ocupara_inmueble1=models.CharField(max_length=30, null=True, blank=True)
    n_ocupara_inmueble2=models.CharField(max_length=30, null=True, blank=True)
    p_ocupara_inmueble2=models.CharField(max_length=30, null=True, blank=True)
    url_domicilio=models.CharField(max_length=255, null=True, blank=True)
    url_ine=models.CharField(max_length=255, null=True, blank=True)
    url_situacion_fiscal=models.CharField(max_length=255, null=True, blank=True)
    n_fiador=models.CharField(max_length=30, null=True, blank=True)
    n2_fiador=models.CharField(max_length=30, null=True, blank=True)
    a_fiador=models.CharField(max_length=30, null=True, blank=True)
    a2_fiador=models.CharField(max_length=30, null=True, blank=True)
    p_fiador=models.CharField(max_length=30, null=True, blank=True)
    tel_fiador=models.PositiveIntegerField(null=True, blank=True)
    tel2_fiador=models.PositiveIntegerField(null=True, blank=True)
    email_fiador=models.CharField(max_length=30,null=True, blank=True)
    estado_civil_fiador=models.CharField(max_length=30, null=True, blank=True)
    calle_fiador=models.CharField(max_length=30, null=True, blank=True)
    municipio_fiador=models.CharField(max_length=30, null=True, blank=True)
    colonia_fiador=models.CharField(max_length=30,null=True, blank=True)
    estado_fiador=models.CharField(max_length=30, null=True, blank=True)
    n_ext_fiador=models.PositiveIntegerField(null=True, blank=True)
    n_int_fiador=models.PositiveIntegerField(null=True, blank=True)
    cp_fiador=models.PositiveIntegerField(null=True, blank=True)
    referencias_fiador=models.CharField(max_length=30, null=True, blank=True)
    empleador_empresa_fiador=models.CharField(max_length=30, null=True, blank=True)
    empleador_profesion_fiador=models.CharField(max_length=30, null=True, blank=True)
    empleador_tel_fiador=models.PositiveIntegerField(null=True, blank=True)
    empleador_ingreso_fiador=models.PositiveIntegerField(null=True, blank=True)
    recibos=models.CharField(max_length=18, null=True, blank=True)
    created=models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated=models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        db_table = 'PersonaFisica'

class form_test(models.Model):
    id = models.AutoField(primary_key=True)
    user=models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    nombre=models.CharField(max_length=30)
    nombre1=models.CharField(max_length=30)

    class Meta:
        db_table = 'PRUEBAS'

class inmuebles(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL )
    alies_inmueble = models.CharField(max_length=30, null=True, blank=True)
    renta = models.CharField(max_length=30, null=True, blank=True)
    valor_inmueble = models.CharField(max_length=30, null=True, blank=True)
    clave_catastral = models.CharField(max_length=30, null=True, blank=True)
    tipo_inmueble = models.CharField(max_length=30, null=True, blank=True)
    uso_inmubele= models.CharField(max_length=30, null=True, blank=True)
    estatus = models.CharField(max_length=30, null=True, blank=True)
    postal_code = models.CharField(max_length=30, null=True, blank=True)
    municipio_alcaldia = models.CharField(max_length=30, null=True, blank=True)
    colonia = models.CharField(max_length=30, null=True, blank=True)
    calle = models.CharField(max_length=30, null=True, blank=True)
    estado  = models.CharField(max_length=30, null=True, blank=True)
    numeroExterior = models.CharField(max_length=30, null=True, blank=True)
    numeroInterior = models.CharField(max_length=30, null=True, blank=True)
    calle1 = models.CharField(max_length=30, null=True, blank=True)
    calle2 = models.CharField(max_length=30, null=True, blank=True)
    n_baños  = models.CharField(max_length=30, null=True, blank=True)
    n_recamaras = models.CharField(max_length=30, null=True, blank=True)
    garaje = models.CharField(max_length=30, null=True, blank=True)
    terrenoTotal = models.CharField(max_length=30, null=True, blank=True)
    terrenoContruido  = models.CharField(max_length=30, null=True, blank=True)
    jardin = models.CharField(max_length=30, null=True, blank=True)
    estacionamiento = models.CharField(max_length=30, null=True, blank=True)
    mascotas  = models.CharField(max_length=30, null=True, blank=True)
    caracteristicasExtra= models.CharField(max_length=30, null=True, blank=True)
    internet  = models.CharField(max_length=30, null=True, blank=True)
    electricidad  = models.CharField(max_length=30, null=True, blank=True)
    televisionCable = models.CharField(max_length=30, null=True, blank=True)
    lineaTelefonica = models.CharField(max_length=30, null=True, blank=True)
    camarasSeguridad  = models.CharField(max_length=30, null=True, blank=True)
    drenaje = models.CharField(max_length=30, null=True, blank=True)
    aguaPotable  = models.CharField(max_length=30, null=True, blank=True)
    gas = models.CharField(max_length=30, null=True, blank=True)
    serviciosExtra = models.CharField(max_length=30, null=True, blank=True)
    fotosInmueble = models.CharField(max_length=30, null=True, blank=True)


    class Meta:
        db_table = 'Inmuebles'





  